### ISSUE TITLE
Can this EFI work on fl5900u with x556uqk main board?

### ISSUE THREAD

**Issue by mokeeqian** [nikhil19rathore99/Hackbook#1]
My computer is ASUS fl5900u, has the same main board model with you

**Comment by nikhil19rathore99** [comment]
> My computer is ASUS fl5900u, has the same main board model with you

Try check the efi with your computer

**Comment by mokeeqian** [comment]
okey. I'll have a try.
Thank you.












mokeeQian
mokeeqian@qq.com


---Original---
